name: build

on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install dependencies for controller
        run: npm ci
        working-directory: ./controller

      - name: Build controller
        run: npm run build:ng
        working-directory: ./controller

      - name: Install dependencies for editor
        run: npm ci
        working-directory: ./editor

      - name: Build editor
        run: npm run build:ng
        working-directory: ./editor
