name: installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18

      - name: Install dependencies for controller
        run: npm ci
        working-directory: ./controller

      - name: Build controller
        run: npm run build:ng
        working-directory: ./controller

      - name: Publish controller
        uses: actions/upload-artifact@v3.1.2
        with:
          name: angular-controller
          path: ./controller/dist/controller
          if-no-files-found: error

      - name: Install dependencies for editor
        run: npm ci
        working-directory: ./editor

      - name: Build editor
        run: npm run build:ng
        working-directory: ./editor

      - name: Publish editor
        uses: actions/upload-artifact@v3.1.2
        with:
          name: angular-editor
          path: ./editor/dist/editor
          if-no-files-found: error

  installer:
    name: Compile installer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    needs: package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18

      - name: Create temp directory
        run: |
          mkdir -p artifacts/controller
          mkdir -p artifacts/editor
          mkdir -p artifacts/sing-box

      - name: Download angular-controller
        uses: actions/download-artifact@v2.1.1
        with:
          name: angular-controller
          path: artifacts/controller

      - name: Download angular-editor
        uses: actions/download-artifact@v2.1.1
        with:
          name: angular-editor
          path: artifacts/editor

      - name: Download sing-box for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget -O ./sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.1.6/sing-box-1.1.6-linux-amd64.tar.gz
          tar -xvzf ./sing-box.tar.gz -C ./artifacts/sing-box
          mv artifacts/sing-box/**/sing-box controller/resources/sing-box

      - name: Download sing-box for Mac
        if: matrix.os == 'macOS-latest'
        run: |
          wget -O ./sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.1.6/sing-box-1.1.6-darwin-amd64.tar.gz
          tar -xvzf ./sing-box.tar.gz -C ./artifacts/sing-box
          mv artifacts/sing-box/**/sing-box controller/resources/sing-box

      - name: Download sing-box for Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-RestMethod -Uri https://github.com/SagerNet/sing-box/releases/download/v1.1.6/sing-box-1.1.6-windows-amd64.zip -OutFile sing-box.zip
          Expand-Archive .\sing-box.zip -DestinationPath .\artifacts\sing-box
          Move-Item -Path .\artifacts\sing-box\**\sing-box.exe -Destination .\controller\resources\sing-box\

      - name: Preparing files
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          mv ./artifacts/controller/* ./singland/controller
          mv ./artifacts/editor/* ./singland/editor
          mv ./controller/resources ./singland/resources

      - name: Preparing files
        if: matrix.os == 'windows-latest'
        run: |
          Move-Item -Path .\artifacts\controller\* -Destination .\singland\controller
          Move-Item -Path .\artifacts\editor\* -Destination .\singland\editor
          Move-Item -Path .\controller\resources -Destination .\singland\resources

      - name: Install dependencies for singland
        run: npm ci
        working-directory: ./singland

      - name: Build
        run: npm run build
        working-directory: ./singland

      - name: Publish installer for Linux
        uses: actions/upload-artifact@v3.1.2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: installer-linux-amd64
          path: |
            ./singland/release/singland-*.tar.gz
            ./singland/release/singland_*_amd64.deb
            ./singland/release/singland-*.x86_64.rpm
          if-no-files-found: error

      - name: Publish installer for Mac
        uses: actions/upload-artifact@v3.1.2
        if: matrix.os == 'macOS-latest'
        with:
          name: installer-mac-amd64
          path: |
            ./singland/release/singland-*-mac.tar.gz
            ./singland/release/singland-*.dmg
          if-no-files-found: error

      - name: Publish installer for Windows
        uses: actions/upload-artifact@v3.1.2
        if: matrix.os == 'windows-latest'
        with:
          name: installer-windows-amd64
          path: |
            ./singland/release/singland*.exe
            ./singland/release/singland-*-win.zip
          if-no-files-found: error
